wp:
    name: wordpress
    port: "80"
    images:
        - ubuntu
        - mysql
        - apache
        - php-apache
        - wordpress
    containers:
        - mysql
        - wordpress
    links:
        - mysql

redis:
    name: redis
    port: "6379"
    images:
        - ubuntu
        - redis
    containers:
        - redis

mongo:
    name: mongodb
    port: "27017"
    images:
        - ubuntu
        - mongodb
    containers:
        - mongodb

rails:
    name: rails-sample-app
    port: "3000"
    images:
        - ubuntu
        - ruby
        - ruby-rails
        - rails-sample-app
    containers:
        - rails-sample-app

ssg:
    name: ssg
    port: "3000"
    images:
        - ubuntu
        - postgres
        - ruby
        - ruby-rails
        - ssg
    containers:
        - postgres
        - ssg
    links:
        - postgres

discourse:
    name: discourse
    port: "3000"
    images:
        - ubuntu
        - postgres
        - redis
        - ruby
        - ruby-rails
        - discourse
    containers:
        - postgres
        - discourse
        - redis
    links:
        - postgres
        - redis
