wp:
    id:
        image: wordpress
        name: wp
        port: "80"
    images:
        - ubuntu
        - mysql
        - apache
        - php-apache
        - wordpress
    links:
        - {image: mysql, name: mysql-wp}

redis:
    id:
        image: redis
        name: redis
        port: "6379"
    images:
        - ubuntu
        - redis

mongo:
    id:
        image: mongodb
        name: mongodb
        port: "27017"
    images:
        - ubuntu
        - mongodb

rails:
    id:
        image: rails-sample-app
        name: rails-sample-app
        port: "3000"
    images:
        - ubuntu
        - ruby
        - ruby-rails
        - rails-sample-app

ssg:
    id:
        image: ssg
        name: ssg
        port: "3000"
    images:
        - ubuntu
        - postgres
        - ruby
        - ruby-rails
        - ssg
    links:
        - {image: postgres, name: postgres-ssg}

ghost:
    id:
        image: ghost
        name: ghost
        port: "2368"
    images:
        - ubuntu
        - nodejs
        - ghost

hipache:
    id:
        image: hipache
        name: hipache
        port: "80"
    images:
        - ubuntu
        - redis
        - nodejs
        - hipache
    links:
        - {image: redis, name: redis-hipache}
